# Generated by Django 3.2.7 on 2021-10-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0006_alter_resume_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(default='def', max_length=100),
        ),
    ]
