# Generated by Django 3.2.7 on 2021-10-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0007_alter_resume_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='title',
        ),
    ]
