# Generated by Django 3.2.7 on 2021-11-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0009_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='apti_question',
        ),
    ]
