# Generated by Django 3.2.7 on 2021-11-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0010_rename_question_apti_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apti_question',
            name='option1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='apti_question',
            name='option2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='apti_question',
            name='option3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='apti_question',
            name='option4',
            field=models.CharField(max_length=50),
        ),
    ]
