# Generated by Django 3.1.7 on 2022-01-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0012_auto_20220118_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='tech_question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=50)),
                ('option2', models.CharField(max_length=50)),
                ('option3', models.CharField(max_length=50)),
                ('option4', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=10)),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
    ]
