# Generated by Django 3.2.9 on 2022-02-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0015_alter_resume_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobdomains',
            fields=[
                ('jobdomainid', models.IntegerField(primary_key=True, serialize=False)),
                ('jobdomainname', models.CharField(max_length=50)),
                ('jobdomainskill', models.CharField(max_length=50)),
            ],
        ),
    ]
