# Generated by Django 3.2.9 on 2022-04-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0017_auto_20220323_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
